### ISSUE TITLE
Develop cargo-rpm as part of the rpm-rs org?

### ISSUE THREAD

**Issue by newpavlov** [rpm-rs/rpm#151]
`carg-rpm` is currently [unmaintained](https://github.com/iqlusioninc/cargo-rpm/issues/96), but still used relatively widely. @tarcieri is [willing](https://github.com/cat-in-136/cargo-generate-rpm/issues/33) to transfer ownership of the crate. I think it would make sense to maintain a Cargo plugin around the `rpm` crate as part of the `rpm-rs` org. Having it part of the org should help with keeping the plugin updated on new `rpm` releases and improve discoverability.

I think it can start as transfer of the `cargo-generate-rpm` crate, of course assuming @cat-in-136 is willing to join the org.

**Comment by dralley** [comment]
I would prefer we don't duplicate any work that is being done or maintained more actively elsewhere, and it seems like `rust2rpm` and `cargo-generate-rpm` are well maintained already.

I don't personally feel comfortable asking cat-in-136 to transfer their crate as there's nothing wrong with the status quo.  If they wanted to or reached out or had signaled that they weren't going to continue working on it, that would be different, but otherwise I'm not going to go around asking that sort of thing.  It's their project and it's fine as is.

Of course, if they want to join the org I'm perfectly OK with that.

**Comment by tarcieri** [comment]
FWIW I offered the `cargo-rpm` crate name to @cat-in-136 and they declined.

I think `cargo-generate-rpm` is in much better shape as it uses `rpm-rs` rather than being an `rpmbuild` wrapper, which eliminates an external dependency and makes it easier to use.
